### ISSUE TITLE
Can't find the game

### ISSUE THREAD

**Issue by jeffrydane** [pauloalves86/go_dino#1]
in dino_api.py line 59, screenshotter.monitors[1:-1] return [ ]
so the program can't play the dino game

in previous commit i try to change screenshotter.monitors[1:-1] to screenshotter.monitors[1:], somehow it works

but not in this commit.

can you give step-by-step how to setting to exactly run this program?

**Comment by pauloalves86** [comment]
I've just committed a fix for this, let me know if it works. If it does not work, could you tell me your OS?

Previously one should run the game on the main monitor, but it is not the case anymore.

**Comment by marianpavel** [comment]
Hi, I am getting Cannot find the game, I run on OS X. Any help would be appreciated

**Comment by pauloalves86** [comment]
Hi @marianpavel, do you use multiple monitor? If so, is the game running on the main monitor? If not, could you try running the game on it?

**Comment by marianpavel** [comment]
Hi @pauloalves86 , no, I am not using 2 monitors, only the MacBook. I use pycharm, installed all the requirements. Trying to run trainer.py with the chrome original game marked as offline in another corner visible. Also tried other online games, none of them are detected.

**Comment by pauloalves86** [comment]
@marianpavel, can you confirm if the fix works?

**Comment by marianpavel** [comment]
@pauloalves86 doesn't work, will try to set up it on windows to see if it works. 

I don't know the cv2 library how is working, I don't think it can find the game.

**Comment by pauloalves86** [comment]
@marianpavel, put this code `image.save('monitor_{:.2f}.jpg'.format(threshold))` after _line 60_ at _dino_api.py_ and tell me if it creates two images and the dino appear on both of them, please.

**Comment by marianpavel** [comment]
@pauloalves86 it creates only 1 image and the dyno appear in it.
![monitor_0 70](https://user-images.githubusercontent.com/8260460/41433409-97c7b8c6-7021-11e8-85c1-8d3700873df8.jpg)
