### ISSUE TITLE
No best file is saved

### ISSUE THREAD

**Issue by marianpavel** [pauloalves86/go_dino#2]
I have tested the latest version on mac, now it works, however, I don't think it saves the results because I've let the program running like 20 minutes and the output command was still jump.

**Comment by pauloalves86** [comment]
@marianpavel, could you add here a screenshot of the game over? I'll try to solve that problem once and for all.

**Comment by marianpavel** [comment]
<img width="1419" alt="screen shot 2018-06-15 at 17 11 24" src="https://user-images.githubusercontent.com/8260460/41472475-328521c6-70bf-11e8-990c-6a30d9ae2963.png">
Hope it helps! Looking forward your answer
P.S. the score of 2066 is made by me :), bot is only jumping.
