### ISSUE TITLE
Cannot import name 'nn' - Why???

### ISSUE THREAD

**Issue by sahithyandev** [pauloalves86/go_dino#4]
ImportError: cannot import name 'nn'
This error raised when i run trainer.py

**Comment by pauloalves86** [comment]
You may have installed the wrong neat.
Run the following and this must end:
`pip uninstall neat WebOb`
`pip install neat-python`

**Comment by pauloalves86** [comment]
Since I have not received a response, I'm closing this. Feel free to comment or reopen if the solution does not work.
