### ISSUE TITLE
pywintypes.error: (6, 'CreateFile', 'The handle is invalid.')

### ISSUE THREAD

**Issue by j-arpit** [pauloalves86/go_dino#5]
I am getting this error in  dino_dummy.py

**Comment by pauloalves86** [comment]
I wasn't able to reproduce this problem. Please, check if every dependency is the right one. Have you installed thru requirements.txt?

**Comment by j-arpit** [comment]
Yes, Same error 

![screenshot 104](https://user-images.githubusercontent.com/29611145/49856683-77f3c480-fe16-11e8-8f53-394a24bd367f.png)

**Comment by pauloalves86** [comment]
Nice! I was able to reproduce. Execute through `cmd` or `powershell` and it's going to work.

**Comment by j-arpit** [comment]
getting a new error:  Can't find the game!
![screenshot 105](https://user-images.githubusercontent.com/29611145/49865058-f0b04c00-fe29-11e8-8474-7cfaaf16c13c.png)

**Comment by pauloalves86** [comment]
Open https://chromedino.com/ with any browser and let it visible, you may put those windows side-by-side.

**Comment by j-arpit** [comment]
getting this new error.
![screenshot 106](https://user-images.githubusercontent.com/29611145/49885642-cf695300-fe5d-11e8-95b2-3af1b89e2eff.png)

**Comment by pauloalves86** [comment]
The only difference I see is that I use `opencv-contrib-python` and you use `opencv-python`. Try remove yours and install the contrib one.
